import { SQLiteDatabase } from 'react-native-sqlite-storage';

const createTbRegistro = (db: SQLiteDatabase) => {
  const query = `CREATE TABLE IF NOT EXISTS TBREGISTRO (
    DFIDREGISTROAPP INTEGER PRIMARY KEY AUTOINCREMENT,
    DFIDREGISTRO INTEGER(11) NULL DEFAULT NULL,
    DFDATAREGISTRO DATE NULL DEFAULT NULL,
    DFHORAREGISTRO TIME NULL DEFAULT NULL,
    DFLOCALIZACAO GEOMETRY NULL DEFAULT NULL,
    DFTIPOREGISTRO VARCHAR(1) NULL DEFAULT NULL,
    DFIDITEMCOLETA INTEGER(11) NULL DEFAULT NULL,
    DFIDITEMCOLETAAPP INTEGER(11) NULL DEFAULT NULL,
    DFIDCOLETA INTEGER(11) NULL DEFAULT NULL,
    DFIDCOLETAAPP INTEGER(11) NULL DEFAULT NULL,
    DFOBSERVACAO VARCHAR(100) NOT NULL,
    DFIMEI VARCHAR(100) NOT NULL,
    DFIDCARRETEIRO VARCHAR(11) NOT NULL,
    DFREGISTROENVIADO VARCHAR(1) NULL DEFAULT 'N',
    CONSTRAINT FK_ItemColeta FOREIGN KEY (DFIDITEMCOLETAAPP) REFERENCES TBITEMCOLETA (DFIDITEMCOLETAAPP),
    CONSTRAINT FK_Coleta FOREIGN KEY (DFIDCOLETAAPP) REFERENCES TBCOLETA (DFIDCOLETAAPP)
    CONSTRAINT FK_Carreteiro FOREIGN KEY (DFIDCARRETEIRO) REFERENCES TBCARRETEIRO (DFIDCARRETEIRO));`;
  db.transaction(
    tx => {
      tx.executeSql(query, [], (_, results) => {
        if (results.rows.length >= 0) return true;
        return false;
      });
    },
    () => createTbRegistro(db),
  );
};

export { createTbRegistro };
