import { SQLiteDatabase } from 'react-native-sqlite-storage';

const createTbVinculoDispositivo = (db: SQLiteDatabase) => {
  const query = `
  CREATE TABLE IF NOT EXISTS TBVINCULODISPOSITIVO (
    DFIDVINCULODISPOSITIVO INTEGER(11) PRIMARY KEY NOT NULL,
    DFIDCARRETEIRO INTEGER(11) NULL DEFAULT NULL,
    DFIDLICENÇA INTEGER(50) NULL DEFAULT NULL,
    DFDATAVINCULO DATE NULL DEFAULT NULL,
    DFHORAVINCULO TIME NULL DEFAULT NULL,
    DFDATAINSTALACAO DATE NULL DEFAULT NULL,
    DFHORAINSTALACAO TIME NULL DEFAULT NULL,
    DFVERSAOAPP VARCHAR(100) NULL DEFAULT NULL,
    DFSO VARCHAR(100) NULL DEFAULT NULL,
    DFVERSAOSO VARCHAR(100) NULL DEFAULT NULL,
    DFMODELOAPARELHO VARCHAR(100) NULL DEFAULT NULL,
    DFESPACOUTILIZADO DOUBLE NULL DEFAULT NULL,
    DFESPACOTOTAL DOUBLE NULL DEFAULT NULL,
    DFMEMORIARAM DOUBLE NULL DEFAULT NULL,
    DFCPU DOUBLE NULL DEFAULT NULL,

    FOREIGN KEY (DFIDCARRETEIRO) REFERENCES TBCARRETEIRO (DFIDCARRETEIRO)
  )
  `;
  db.transaction(
    tx => {
      tx.executeSql(query, [], (_, results) => {
        if (results.rows.length >= 0) {
          return true;
        }
      });
    },
    () => createTbVinculoDispositivo(db),
  );
};

export { createTbVinculoDispositivo };
