import { SQLiteDatabase } from 'react-native-sqlite-storage';

const createTbColeta = (db: SQLiteDatabase) => {
  const query = `CREATE TABLE IF NOT EXISTS TBCOLETA (
    DFIDCOLETAAPP INTEGER PRIMARY KEY AUTOINCREMENT,
    DFORDEMCOLETA INTEGER NOT NULL DEFAULT NULL,
    DFIDCOLETAERP INTEGER(11) NULL DEFAULT NULL,
    DFIDCOLETA INTEGER NULL,
    DFIDCARRETEIRO INTEGER(11) NOT NULL,
    DFIDLINHA INTEGER(11) NULL DEFAULT NULL,
    DFIDVEICULO INTEGER(11) NULL DEFAULT NULL,
    DFIDREGIONAL INTEGER(11) NULL DEFAULT NULL,
    DFDATACOLETA DATE NULL DEFAULT '',
    DFHORACOLETA TIME NULL DEFAULT '',
    DFDATASAIDA DATE NULL DEFAULT '',
    DFHORASAIDA TIME NULL DEFAULT '',
    DFDATAPROGRAMADA TIME NULL DEFAULT '',
    DFIMEI VARCHAR(25) NULL DEFAULT NULL,
    DFSTATUS VARCHAR(1) NOT NULL DEFAULT NULL,
    DFCOLETASICRONIZADA VARCHAR(1) NULL DEFAULT 'N',
    DFKMINICIAL DOUBLE NOT NULL DEFAULT '0',
    DFKMFINAL DOUBLE NOT NULL DEFAULT '0',
    DFBLOQUEIOERP VARCHAR(1) NULL DEFAULT 'N',
    CONSTRAINT FK_Carreteiro FOREIGN KEY (DFIDCARRETEIRO) REFERENCES TBCARRETEIRO 
    (DFIDCARRETEIRO),
    CONSTRAINT FK_Linha FOREIGN KEY (DFIDLINHA) REFERENCES TBLINHA  (DFIDLINHA),
    CONSTRAINT FK_Veiculo FOREIGN KEY (DFIDVEICULO) REFERENCES TBVEICULO (DFIDVEICULO),
    CONSTRAINT FK_Regional FOREIGN KEY (DFIDREGIONAL) REFERENCES TBREGIONAL (DFIDREGIONAL));`;
  db.transaction(
    tx => {
      tx.executeSql(query, [], (_, results) => {
        if (results.rows.length >= 0) {
          return true;
        }
      });
    },
    () => createTbColeta(db),
  );
};

export { createTbColeta };
